version: '3.8'

services:
  app:
    build: .
    env_file: .env
    container_name: finance-api-app
    ports:
      - "8080:8080"
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: finance-db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: finance-pgadmin
    restart: always

    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata: