version: '3.8'

services:
  app:
    build: .
    container_name: finance-api-app
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: finance-db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: finance-pgadmin
    restart: always
    env_file: .env
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
